### ISSUE TITLE
The text area should have a different color

### ISSUE THREAD

**Issue by kiy4h** [walterbender/story#16]
To me, it's a bit confusing to think where the text area starts and ends. A light grey would be a better color for the text area and the buttons at bottom-right.

**Comment by JuiP** [comment]
#20 merged; closes this issue.
Decided to go with a white background which is demarcated by boundaries. Screenshot in this [comment](https://github.com/sugarlabs/story/pull/20#issuecomment-671076350)
@quozl @chimosky

**Comment by quozl** [comment]
Is close issue button not available for you?  :grinning:

**Comment by JuiP** [comment]
No, I do not have the rights to close issues I haven't raised. :sweat_smile:

**Comment by quozl** [comment]
Ah, I see, thanks.
